version: "3.8"

services:
  app:
    image: python:3.12.2-slim
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      # Add other environment variables if needed
